pipeline:
  name: ci-build-pipeline
  identifier: Build_Assignment
  projectIdentifier: Harness_Inc_Assignment
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: Assignment_Connector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  name: Build and Push
                  identifier: Build_and_Push
                  type: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: account.harnessImage
                    repo: docker-local/harness-demo-app
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: ./Dockerfile
                    context: .
        delegateSelectors:
          - harness-delegate
