pipeline:
  name: Build - Assignment
  identifier: Build_Assignment
  projectIdentifier: Harness_Inc_Assignment
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Assignment_Connector
        build: <+input>
  stages:
    - stage:
        name: Build and Push
        identifier: Build_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: account.harnessImage
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: <+stage.variables.DockerRepo>
                    tags:
                      - <+stage.variables.Tags>
