pipeline:
  name: ci-cd-pipeline
  identifier: cicdpipeline
  projectIdentifier: Harness_Inc_Assignment
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Assignment_Connector
        build: <+input>
  stages:
    - stage:
        name: Build and Push
        identifier: Build_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Docker Image
                  identifier: Build_Docker_Image
                  spec:
                    shell: Sh
                    image: docker:28-cli
                    privileged: true
                    command: |
                      docker build \
                        -t harness-demo-app:<+pipeline.sequenceId> \
                        .
              - step:
                  type: Run
                  name: Push Image to JFrog
                  identifier: Push_Image
                  spec:
                    shell: Sh
                    image: docker:28-cli
                    privileged: true
                    command: |

                      docker login trialtfe0xb.jfrog.io \
                        -u "<+secrets.getValue('jfrog_username')>" \
                        -p "<+secrets.getValue('jfrog_token')>"

                      docker tag \
                        harness-demo-app:<+pipeline.sequenceId> \
                        trialtfe0xb.jfrog.io/docker-local-docker/harness-demo-app:<+pipeline.sequenceId>

                      docker tag \
                        harness-demo-app:<+pipeline.sequenceId> \
                        trialtfe0xb.jfrog.io/docker-local-docker/harness-demo-app:latest

                      docker push \
                        trialtfe0xb.jfrog.io/docker-local-docker/harness-demo-app:<+pipeline.sequenceId>

                      docker push \
                        trialtfe0xb.jfrog.io/docker-local-docker/harness-demo-app:latest
    - stage:
        name: Deployment Approval
        identifier: Deployment_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Deployment Approval
                  identifier: Deployment_Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: true
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: harnessdemo
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: harnessdemo
                          type: ArtifactoryRegistry
                          spec:
                            artifactPath: <+input>
                            tag: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessdemo
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: false
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - step:
                  type: HarnessApproval
                  name: Proceed for Rolling Deployment
                  identifier: Proceed_for_Rolling_Deployment
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: true
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - harness-delegate
