pipeline:
  name: ci-pipeline-build
  identifier: cipipelinebuild
  projectIdentifier: Harness_Inc_Assignment
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Assignment_Connector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    image: docker:28
                    command: docker build -t harness-demo-app .
